services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wooseoki
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds